#!/bin/bash
# Web bot rate-limiting: nginx limit_req / apache mod_qos throttle the families in /etc/hestia/botfamilies.conf
# with a 429, per domain off, lenient or strict (web.conf BOTLIMIT). Humans are never limited.
# Families match on the User-Agent unverified, so a spoofed UA can drain a real crawler's bucket on that domain.

# /etc/hestia survives updates, so the shipped table is only a seed.
botpolicy_seed_families() {
	mkdir -p "$CONF_DIR"
	[ -f "$CONF_DIR/botfamilies.conf" ] \
		|| cp -f "$HESTIA/share/hestia/botfamilies.conf" "$CONF_DIR/botfamilies.conf"
}

# "120r/m" -> "120 60"; "2r/s" -> "2 1" (count + window seconds for mod_qos). Fallback "60 60".
botpolicy_rate_to_qos() {
	local r="$1" n u
	n=${r%%r/*}
	u=${r##*r/}
	case "$u" in s) echo "${n:-60} 1" ;; *) echo "${n:-60} 60" ;; esac
}

# The UA map plus two limit_req zones per enabled family. 'generic' goes last in the map: the first match wins.
botpolicy_render_nginx() {
	local obj="$CONF_DIR/botfamilies"
	local out="/etc/nginx/conf.d/hestia_botlimit.conf"
	[ -f "$obj.conf" ] || return 0

	local enabled f match len strict has_generic=''
	enabled=$(search_objects "$obj" 'ENABLED' 'yes' 'FAMILY')

	local tmp
	tmp=$(mktemp)
	{
		echo "# HestiaRE web bot rate-limit (Layer B) - GENERATED from $obj.conf. Edit the conf,"
		echo "# then run h-update-sys-botfamilies to re-render. Do not edit this file directly."
		echo "limit_req_status 429;"
		echo
		echo "map \$http_user_agent \$hbot_fam {"
		echo "	default \"\";"
		for f in $enabled; do
			[ "$f" = 'generic' ] && {
				has_generic=1
				continue
			}
			match=$(get_object_value "$obj" 'FAMILY' "$f" '$MATCH')
			[ -n "$match" ] && echo "	\"~*($match)\" \"$f\";"
		done
		if [ -n "$has_generic" ]; then
			match=$(get_object_value "$obj" 'FAMILY' 'generic' '$MATCH')
			[ -n "$match" ] && echo "	\"~*($match)\" \"generic\";"
		fi
		echo "}"
		echo
		# $host inside the map value, not on the zone key: each domain gets its own bucket per family, and a
		# non-family UA still maps to "" and stays unlimited. 2m holds about 32k host:family keys per zone.
		for f in $enabled; do
			len=$(get_object_value "$obj" 'FAMILY' "$f" '$LENIENT')
			strict=$(get_object_value "$obj" 'FAMILY' "$f" '$STRICT')
			echo "map \$hbot_fam \$hbot_k_$f { default \"\"; \"$f\" \"\$host:$f\"; }"
			[ -n "$len" ] && echo "limit_req_zone \$hbot_k_$f zone=hbot_${f}_lenient:2m rate=$len;"
			[ -n "$strict" ] && echo "limit_req_zone \$hbot_k_$f zone=hbot_${f}_strict:2m rate=$strict;"
		done
	} > "$tmp"
	mv -f "$tmp" "$out"
	chmod 644 "$out"
}

# mod_qos counts per client IP, not per domain; the per-domain fragment sets the QS_Event_<fam>_<level> it counts.
botpolicy_render_apache() {
	local obj="$CONF_DIR/botfamilies"
	local out="/etc/apache2/conf.d/hestia_botlimit.conf"
	[ -f "$obj.conf" ] || return 0

	local enabled f len strict n win
	enabled=$(search_objects "$obj" 'ENABLED' 'yes' 'FAMILY')
	local tmp
	tmp=$(mktemp)
	{
		echo "# HestiaRE web bot rate-limit (Layer B, apache mod_qos) - GENERATED from $obj.conf."
		echo "# Edit the conf, then run h-update-sys-botfamilies. Do not edit this file directly."
		echo "QS_ClientEntries 100000"
		echo "QS_ErrorResponseCode 429"
		for f in $enabled; do
			len=$(get_object_value "$obj" 'FAMILY' "$f" '$LENIENT')
			strict=$(get_object_value "$obj" 'FAMILY' "$f" '$STRICT')
			read -r n win < <(botpolicy_rate_to_qos "$len")
			echo "QS_ClientEventLimitCount $n $win QS_Event_${f}_lenient"
			read -r n win < <(botpolicy_rate_to_qos "$strict")
			echo "QS_ClientEventLimitCount $n $win QS_Event_${f}_strict"
		done
	} > "$tmp"
	mv -f "$tmp" "$out"
	chmod 644 "$out"
}

# A family that is gone or disabled has no zone in the server config, so a fragment naming it fails
# `nginx -t` for the whole box. Asked by both the renderer and the restore's report.
botpolicy_family_enabled() {
	[ "$(get_object_value "$CONF_DIR/botfamilies" 'FAMILY' "$1" '$ENABLED' 2> /dev/null)" = 'yes' ]
}

# The domain's BOTLIMIT ("fam:level,fam:level", absent = off) as nginx.botlimit.conf or botlimit.apache2.conf.
# Removed when empty, so the vhost's include glob is a no-op for an unthrottled domain.
botpolicy_render_domain_fragment() {
	local user="$1" domain="$2" sys
	if [ -n "$PROXY_SYSTEM" ]; then sys="$PROXY_SYSTEM"; else sys="$WEB_SYSTEM"; fi

	local rec bl
	rec=$(grep -m1 -F "DOMAIN='$domain'" "$CONF_DIR/users/$user/web.conf" 2> /dev/null)
	[ -n "$rec" ] || return 0
	bl=$(sed -n "s/.*BOTLIMIT='\([^']*\)'.*/\1/p" <<< "$rec")

	local obj="$CONF_DIR/botfamilies"
	local frag tmp entry fam lvl burst nodelay nd match
	tmp=$(mktemp)

	if [ "$sys" = "nginx" ]; then
		frag="$HOMEDIR/$user/conf/web/$domain/nginx.botlimit.conf"
		# shellcheck disable=SC2086 # comma-split of the compact BOTLIMIT field is intentional
		local -a _entry_list
		IFS=, read -ra _entry_list <<< "$bl"
		for entry in "${_entry_list[@]}"; do
			[ -n "$entry" ] || continue
			fam=${entry%%:*}
			lvl=${entry#*:}
			case "$lvl" in lenient | strict) ;; *) continue ;; esac
			botpolicy_family_enabled "$fam" || continue
			burst=$(get_object_value "$obj" 'FAMILY' "$fam" '$BURST' 2> /dev/null)
			nodelay=$(get_object_value "$obj" 'FAMILY' "$fam" '$NODELAY' 2> /dev/null)
			[ -n "$burst" ] || burst=10
			nd=""
			[ "$nodelay" = "yes" ] && nd=" nodelay"
			echo "limit_req zone=hbot_${fam}_${lvl} burst=${burst}${nd};" >> "$tmp"
		done
	elif [ "$sys" = "apache2" ]; then
		frag="$HOMEDIR/$user/conf/web/$domain/botlimit.apache2.conf"
		# shellcheck disable=SC2086 # comma-split of the compact BOTLIMIT field is intentional
		local -a _entry_list
		IFS=, read -ra _entry_list <<< "$bl"
		for entry in "${_entry_list[@]}"; do
			[ -n "$entry" ] || continue
			fam=${entry%%:*}
			lvl=${entry#*:}
			case "$lvl" in lenient | strict) ;; *) continue ;; esac
			botpolicy_family_enabled "$fam" || continue
			match=$(get_object_value "$obj" 'FAMILY' "$fam" '$MATCH' 2> /dev/null)
			[ -n "$match" ] || continue
			echo "BrowserMatchNoCase \"$match\" hbot_$fam" >> "$tmp"
			echo "SetEnvIf hbot_$fam 1 QS_Event_${fam}_${lvl}" >> "$tmp"
		done
	else
		rm -f "$tmp"
		return 0
	fi

	if [ -s "$tmp" ]; then
		mv -f "$tmp" "$frag"
		chown root:"$user" "$frag"
		chmod 640 "$frag"
	else
		rm -f "$tmp" "$frag"
	fi
}

# Fragments reference zones by family name, so every change to the family table needs this, or stale references
# stay until the next domain rebuild.
botpolicy_render_all_fragments() {
	local wc u d
	for wc in "$CONF_DIR"/users/*/web.conf; do
		[ -f "$wc" ] || continue
		u=$(basename "$(dirname "$wc")")
		# shellcheck disable=SC2013 # a Hestia domain cannot contain whitespace
		for d in $(sed -n "s/^DOMAIN='\([^']*\)'.*BOTLIMIT='[^']\+.*/\1/p" "$wc"); do
			botpolicy_render_domain_fragment "$u" "$d"
		done
	done
}

# Strips a deleted family from every domain's BOTLIMIT, where it would otherwise be rendered forever.
# Absolute object path: update_object_value resolves a relative one against the caller's own $USER_DATA.
botpolicy_purge_family() {
	local fam="$1" wc u d obj bl new e
	for wc in "$CONF_DIR"/users/*/web.conf; do
		[ -f "$wc" ] || continue
		u=$(basename "$(dirname "$wc")")
		obj="$CONF_DIR/users/$u/web"
		# shellcheck disable=SC2013 # a Hestia domain cannot contain whitespace
		for d in $(sed -n "s/^DOMAIN='\([^']*\)'.*BOTLIMIT='[^']\+.*/\1/p" "$wc"); do
			bl=$(get_object_value "$obj" 'DOMAIN' "$d" '$BOTLIMIT' 2> /dev/null)
			new=''
			# shellcheck disable=SC2086 # comma-split of the compact BOTLIMIT field is intentional
			local -a _e_list
			IFS=, read -ra _e_list <<< "$bl"
			for e in "${_e_list[@]}"; do
				[ -n "$e" ] || continue
				[ "${e%%:*}" = "$fam" ] && continue
				new="${new:+$new,}$e"
			done
			[ "$new" = "$bl" ] && continue
			update_object_value "$obj" 'DOMAIN' "$d" '$BOTLIMIT' "$new"
			botpolicy_render_domain_fragment "$u" "$d"
		done
	done
}
