#!/bin/bash
# HestiaRE web bot rate-limiting (Layer B) - server-native, CrowdSec-independent.
# Native nginx limit_req / apache mod_qos throttling of bot families (429 on excess). Humans are
# UNLIMITED; malicious traffic is CrowdSec's job (ban -> 403), never here. Available on ANY web
# install (nginx-only, apache-only, both), whether or not CrowdSec is installed.
#
# Model: an admin bot-family table (share/hestia/botfamilies.conf, seeded to
# /etc/hestia/botfamilies.conf). Each family = name / UA match / lenient+strict rate / enabled,
# plus conf-only advanced burst + nodelay. Per domain each family is off/lenient/strict (the
# web.conf BOTLIMIT field). nginx keys per family PER DOMAIN ($host:family, so customers don't share
# a bucket); apache mod_qos counts per client IP. get_object_value/search_objects take the object
# base and append .conf.
#
# KNOWN LIMITATION (matching by UA): families are matched on the User-Agent string, which is
# spoofable, and Layer B does NOT verify it (no IP-range / reverse-DNS check). On a non-CrowdSec
# install a client faking e.g. a googlebot UA can therefore drain that family's per-domain bucket and
# get the real Googlebot 429'd (SEO harm) - active abuse, not just evasion. On CrowdSec installs the
# good-actor whitelist verifies real crawlers by rDNS/IP, so a spoofer isn't shielded from bans.
# Accepted for now (verification would need per-request rDNS); revisit if it bites.

# Seed the instance family conf (survives updates) from the shipped default if absent.
botpolicy_seed_families() {
	mkdir -p "$CONF_DIR"
	[ -f "$CONF_DIR/botfamilies.conf" ] \
		|| cp -f "$HESTIA/share/hestia/botfamilies.conf" "$CONF_DIR/botfamilies.conf"
}

# "120r/m" -> "120 60"; "2r/s" -> "2 1" (count + window seconds for mod_qos). Fallback "60 60".
botpolicy_rate_to_qos() {
	local r="$1" n u
	n=${r%%r/*}
	u=${r##*r/}
	case "$u" in s) echo "${n:-60} 1" ;; *) echo "${n:-60} 60" ;; esac
}

# Render the nginx UA map + per-family limit_req zones into /etc/nginx/conf.d/hestia_botlimit.conf.
# Aggregate keying; 'generic' is always emitted LAST in the UA map (first match wins).
botpolicy_render_nginx() {
	local obj="$CONF_DIR/botfamilies"
	local out="/etc/nginx/conf.d/hestia_botlimit.conf"
	[ -f "$obj.conf" ] || return 0

	local enabled f match len strict has_generic=''
	enabled=$(search_objects "$obj" 'ENABLED' 'yes' 'FAMILY')

	local tmp
	tmp=$(mktemp)
	{
		echo "# HestiaRE web bot rate-limit (Layer B) - GENERATED from $obj.conf. Edit the conf,"
		echo "# then run h-update-sys-botfamilies to re-render. Do not edit this file directly."
		echo "limit_req_status 429;"
		echo
		echo "map \$http_user_agent \$hbot_fam {"
		echo "	default \"\";"
		for f in $enabled; do
			[ "$f" = 'generic' ] && {
				has_generic=1
				continue
			}
			match=$(get_object_value "$obj" 'FAMILY' "$f" '$MATCH')
			[ -n "$match" ] && echo "	\"~*($match)\" \"$f\";"
		done
		if [ -n "$has_generic" ]; then
			match=$(get_object_value "$obj" 'FAMILY' 'generic' '$MATCH')
			[ -n "$match" ] && echo "	\"~*($match)\" \"generic\";"
		fi
		echo "}"
		echo
		# Per family: an aggregate key + the two rate zones. The key is "$host:<family>" so the bucket
		# is per-domain (each vhost gets its own family counter) - a busy customer's crawler traffic
		# can't 429 another customer out of the shared server-wide bucket. Crucially $host lives INSIDE
		# the map value (not concatenated onto the zone key), so a non-family UA still maps to "" and is
		# skipped -> humans stay unlimited. Zone count is fixed (families x2), independent of domain
		# count; 2m gives ~32k host:family slots per zone, ample for a many-domain box.
		for f in $enabled; do
			len=$(get_object_value "$obj" 'FAMILY' "$f" '$LENIENT')
			strict=$(get_object_value "$obj" 'FAMILY' "$f" '$STRICT')
			echo "map \$hbot_fam \$hbot_k_$f { default \"\"; \"$f\" \"\$host:$f\"; }"
			[ -n "$len" ] && echo "limit_req_zone \$hbot_k_$f zone=hbot_${f}_lenient:2m rate=$len;"
			[ -n "$strict" ] && echo "limit_req_zone \$hbot_k_$f zone=hbot_${f}_strict:2m rate=$strict;"
		done
	} > "$tmp"
	mv -f "$tmp" "$out"
	chmod 644 "$out"
}

# Render the apache mod_qos base + a per-family per-level event counter into
# /etc/apache2/conf.d/hestia_botlimit.conf. mod_qos counts per client IP (no aggregate), 429 on
# breach; the per-domain fragment sets the QS_Event_<fam>_<level> var.
botpolicy_render_apache() {
	local obj="$CONF_DIR/botfamilies"
	local out="/etc/apache2/conf.d/hestia_botlimit.conf"
	[ -f "$obj.conf" ] || return 0

	local enabled f len strict n win
	enabled=$(search_objects "$obj" 'ENABLED' 'yes' 'FAMILY')
	local tmp
	tmp=$(mktemp)
	{
		echo "# HestiaRE web bot rate-limit (Layer B, apache mod_qos) - GENERATED from $obj.conf."
		echo "# Edit the conf, then run h-update-sys-botfamilies. Do not edit this file directly."
		echo "QS_ClientEntries 100000"
		echo "QS_ErrorResponseCode 429"
		for f in $enabled; do
			len=$(get_object_value "$obj" 'FAMILY' "$f" '$LENIENT')
			strict=$(get_object_value "$obj" 'FAMILY' "$f" '$STRICT')
			read -r n win < <(botpolicy_rate_to_qos "$len")
			echo "QS_ClientEventLimitCount $n $win QS_Event_${f}_lenient"
			read -r n win < <(botpolicy_rate_to_qos "$strict")
			echo "QS_ClientEventLimitCount $n $win QS_Event_${f}_strict"
		done
	} > "$tmp"
	mv -f "$tmp" "$out"
	chmod 644 "$out"
}

# Re-render the active web front's Layer-B server config + reload. nginx fronts in nginx-only/both;
# apache-only is the only model where apache does Layer B.
botpolicy_apply() {
	local pub
	if [ -n "$PROXY_SYSTEM" ]; then pub="$PROXY_SYSTEM"; else pub="$WEB_SYSTEM"; fi
	if [ "$pub" = "nginx" ]; then
		botpolicy_render_nginx
		nginx -t > /dev/null 2>&1 && { systemctl reload nginx > /dev/null 2>&1 || systemctl restart nginx > /dev/null 2>&1; }
	elif [ "$WEB_SYSTEM" = "apache2" ]; then
		botpolicy_render_apache
		apache2ctl configtest > /dev/null 2>&1 && { systemctl reload apache2 > /dev/null 2>&1 || systemctl restart apache2 > /dev/null 2>&1; }
	fi
}

# Render the per-domain Layer-B fragment (nginx.botlimit.conf / botlimit.apache2.conf) from the
# domain's BOTLIMIT field ("fam:level,fam:level"; level = lenient|strict, absent = off). Removed
# when empty, so the vhost's IncludeOptional/include glob is a no-op for unthrottled domains.
#
# A family that is gone or disabled is SKIPPED: the server config only defines zones for enabled
# families, so emitting `limit_req zone=hbot_x_strict` for a disabled one leaves a dangling zone
# reference and `nginx -t` fails - which would block the next reload for every domain on the box.
# botpolicy_family_enabled FAMILY - does this host know the family and have it switched on?
#
# A family that is gone or disabled has no zone in the server config, so a fragment naming it fails
# `nginx -t` for the whole box. Asked from here by both the renderer and the restore's report.
botpolicy_family_enabled() {
	[ "$(get_object_value "$CONF_DIR/botfamilies" 'FAMILY' "$1" '$ENABLED' 2> /dev/null)" = 'yes' ]
}

botpolicy_render_domain_fragment() {
	local user="$1" domain="$2" sys
	if [ -n "$PROXY_SYSTEM" ]; then sys="$PROXY_SYSTEM"; else sys="$WEB_SYSTEM"; fi

	local rec bl
	rec=$(grep -m1 -F "DOMAIN='$domain'" "$CONF_DIR/users/$user/web.conf" 2> /dev/null)
	[ -n "$rec" ] || return 0
	bl=$(sed -n "s/.*BOTLIMIT='\([^']*\)'.*/\1/p" <<< "$rec")

	local obj="$CONF_DIR/botfamilies"
	local frag tmp entry fam lvl burst nodelay nd match
	tmp=$(mktemp)

	if [ "$sys" = "nginx" ]; then
		frag="$HOMEDIR/$user/conf/web/$domain/nginx.botlimit.conf"
		# shellcheck disable=SC2086 # comma-split of the compact BOTLIMIT field is intentional
		local -a _entry_list
		IFS=, read -ra _entry_list <<< "$bl"
		for entry in "${_entry_list[@]}"; do
			[ -n "$entry" ] || continue
			fam=${entry%%:*}
			lvl=${entry#*:}
			case "$lvl" in lenient | strict) ;; *) continue ;; esac
			botpolicy_family_enabled "$fam" || continue
			burst=$(get_object_value "$obj" 'FAMILY' "$fam" '$BURST' 2> /dev/null)
			nodelay=$(get_object_value "$obj" 'FAMILY' "$fam" '$NODELAY' 2> /dev/null)
			[ -n "$burst" ] || burst=10
			nd=""
			[ "$nodelay" = "yes" ] && nd=" nodelay"
			echo "limit_req zone=hbot_${fam}_${lvl} burst=${burst}${nd};" >> "$tmp"
		done
	elif [ "$sys" = "apache2" ]; then
		frag="$HOMEDIR/$user/conf/web/$domain/botlimit.apache2.conf"
		# shellcheck disable=SC2086 # comma-split of the compact BOTLIMIT field is intentional
		local -a _entry_list
		IFS=, read -ra _entry_list <<< "$bl"
		for entry in "${_entry_list[@]}"; do
			[ -n "$entry" ] || continue
			fam=${entry%%:*}
			lvl=${entry#*:}
			case "$lvl" in lenient | strict) ;; *) continue ;; esac
			botpolicy_family_enabled "$fam" || continue
			match=$(get_object_value "$obj" 'FAMILY' "$fam" '$MATCH' 2> /dev/null)
			[ -n "$match" ] || continue
			echo "BrowserMatchNoCase \"$match\" hbot_$fam" >> "$tmp"
			echo "SetEnvIf hbot_$fam 1 QS_Event_${fam}_${lvl}" >> "$tmp"
		done
	else
		rm -f "$tmp"
		return 0
	fi

	if [ -s "$tmp" ]; then
		mv -f "$tmp" "$frag"
		chown root:"$user" "$frag"
		chmod 640 "$frag"
	else
		rm -f "$tmp" "$frag"
	fi
}

# Re-render every throttled domain's fragment. Needed whenever the FAMILY TABLE changes (rename,
# delete, enable/disable): fragments reference zones by family name, so a table change that is not
# followed by this leaves stale references behind until the next domain rebuild.
botpolicy_render_all_fragments() {
	local wc u d
	for wc in "$CONF_DIR"/users/*/web.conf; do
		[ -f "$wc" ] || continue
		u=$(basename "$(dirname "$wc")")
		# shellcheck disable=SC2013 # a Hestia domain cannot contain whitespace
		for d in $(sed -n "s/^DOMAIN='\([^']*\)'.*BOTLIMIT='[^']\+.*/\1/p" "$wc"); do
			botpolicy_render_domain_fragment "$u" "$d"
		done
	done
}

# Strip one family from every domain's BOTLIMIT - for a family that no longer exists, whose leftover
# references would otherwise be rendered forever. Absolute object path: update_object_value resolves a
# relative one against the caller's own $USER_DATA.
botpolicy_purge_family() {
	local fam="$1" wc u d obj bl new e
	for wc in "$CONF_DIR"/users/*/web.conf; do
		[ -f "$wc" ] || continue
		u=$(basename "$(dirname "$wc")")
		obj="$CONF_DIR/users/$u/web"
		# shellcheck disable=SC2013 # a Hestia domain cannot contain whitespace
		for d in $(sed -n "s/^DOMAIN='\([^']*\)'.*BOTLIMIT='[^']\+.*/\1/p" "$wc"); do
			bl=$(get_object_value "$obj" 'DOMAIN' "$d" '$BOTLIMIT' 2> /dev/null)
			new=''
			# shellcheck disable=SC2086 # comma-split of the compact BOTLIMIT field is intentional
			local -a _e_list
			IFS=, read -ra _e_list <<< "$bl"
			for e in "${_e_list[@]}"; do
				[ -n "$e" ] || continue
				[ "${e%%:*}" = "$fam" ] && continue
				new="${new:+$new,}$e"
			done
			[ "$new" = "$bl" ] && continue
			update_object_value "$obj" 'DOMAIN' "$d" '$BOTLIMIT' "$new"
			botpolicy_render_domain_fragment "$u" "$d"
		done
	done
}
